version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bemoreweb
      MYSQL_DATABASE: pdvbemoreweb
      MYSQL_USER: bemoreweb
      MYSQL_PASSWORD: bemoreweb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
